apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg
  labels:
    app: ffmpeg
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: ffmpeg
  template:
    metadata:
      labels:
        app: ffmpeg
    spec:
      containers:
        - name: ffmpeg
          image: bharper7/ffmpeg:v2
          volumeMounts: 
          - mountPath: "/home/user/videos"
            name: files-mount
          ports:
            - containerPort: 5672
          env:
          - name: RABBITMQ_ERLANG_COOKIE
            valueFrom:
              secretKeyRef:
                name: rabbitmq-secret
                key: RABBITMQ_ERLANG_COOKIE
      volumes:
      - name: files-mount
        persistentVolumeClaim:
          claimName: ffmpeg-pvc  