apiVersion: v1
kind: PersistentVolume
metadata:
  name: ffmpeg-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/videos"