apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-deployment
spec:
  scaleTargetRef:
    name: ffmpeg
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: rabbitmq
    metadata:
      host: amqp://EmZn4ScuOPLEU1CGIsFKOaQSCQdjhzca:dJhLl2aVF78Gn07g2yGoRuwjXSc6tT11@192.168.49.2:30861
      mode: QueueLength
      value: "1"
      queueName: files